## 端⼝号 上下⽂路径
server:
  port: 8080
  servlet:
    context-path: /OnlineShopping
## 数据源配置
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1h8323vd93h379wpo.mysql.rds.aliyuncs.com:3306/db_online_shopping?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: js_2022
    password: abc123!!!
## freemarker
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/views/
## 启⽤热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

## mybatis 配置
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.xxxx.crm.vo;com.xxxx.crm.query;com.xxxx.crm.dto
  configuration:
    map-underscore-to-camel-case: true
## pageHelper 分⻚
pagehelper:
  helper-dialect: mysql

## 设置 dao ⽇志打印级别
logging:
  level:
    com:
      xxxx:
         crm:
           dao: debug